// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RouteGetMuteTimingsReader is a Reader for the RouteGetMuteTimings structure.
type RouteGetMuteTimingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetMuteTimingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetMuteTimingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/provisioning/mute-timings] RouteGetMuteTimings", response, response.Code())
	}
}

// NewRouteGetMuteTimingsOK creates a RouteGetMuteTimingsOK with default headers values
func NewRouteGetMuteTimingsOK() *RouteGetMuteTimingsOK {
	return &RouteGetMuteTimingsOK{}
}

/*
RouteGetMuteTimingsOK describes a response with status code 200, with default header values.

MuteTimings
*/
type RouteGetMuteTimingsOK struct {
	Payload models.MuteTimings
}

// IsSuccess returns true when this route get mute timings o k response has a 2xx status code
func (o *RouteGetMuteTimingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route get mute timings o k response has a 3xx status code
func (o *RouteGetMuteTimingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get mute timings o k response has a 4xx status code
func (o *RouteGetMuteTimingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route get mute timings o k response has a 5xx status code
func (o *RouteGetMuteTimingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route get mute timings o k response a status code equal to that given
func (o *RouteGetMuteTimingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the route get mute timings o k response
func (o *RouteGetMuteTimingsOK) Code() int {
	return 200
}

func (o *RouteGetMuteTimingsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/mute-timings][%d] routeGetMuteTimingsOK  %+v", 200, o.Payload)
}

func (o *RouteGetMuteTimingsOK) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/mute-timings][%d] routeGetMuteTimingsOK  %+v", 200, o.Payload)
}

func (o *RouteGetMuteTimingsOK) GetPayload() models.MuteTimings {
	return o.Payload
}

func (o *RouteGetMuteTimingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
