// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RouteGetTemplatesReader is a Reader for the RouteGetTemplates structure.
type RouteGetTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRouteGetTemplatesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/provisioning/templates] RouteGetTemplates", response, response.Code())
	}
}

// NewRouteGetTemplatesOK creates a RouteGetTemplatesOK with default headers values
func NewRouteGetTemplatesOK() *RouteGetTemplatesOK {
	return &RouteGetTemplatesOK{}
}

/*
RouteGetTemplatesOK describes a response with status code 200, with default header values.

NotificationTemplates
*/
type RouteGetTemplatesOK struct {
	Payload models.NotificationTemplates
}

// IsSuccess returns true when this route get templates Ok response has a 2xx status code
func (o *RouteGetTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route get templates Ok response has a 3xx status code
func (o *RouteGetTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get templates Ok response has a 4xx status code
func (o *RouteGetTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route get templates Ok response has a 5xx status code
func (o *RouteGetTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route get templates Ok response a status code equal to that given
func (o *RouteGetTemplatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the route get templates Ok response
func (o *RouteGetTemplatesOK) Code() int {
	return 200
}

func (o *RouteGetTemplatesOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates][%d] routeGetTemplatesOk  %+v", 200, o.Payload)
}

func (o *RouteGetTemplatesOK) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates][%d] routeGetTemplatesOk  %+v", 200, o.Payload)
}

func (o *RouteGetTemplatesOK) GetPayload() models.NotificationTemplates {
	return o.Payload
}

func (o *RouteGetTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteGetTemplatesNotFound creates a RouteGetTemplatesNotFound with default headers values
func NewRouteGetTemplatesNotFound() *RouteGetTemplatesNotFound {
	return &RouteGetTemplatesNotFound{}
}

/*
RouteGetTemplatesNotFound describes a response with status code 404, with default header values.

	Not found.
*/
type RouteGetTemplatesNotFound struct {
}

// IsSuccess returns true when this route get templates not found response has a 2xx status code
func (o *RouteGetTemplatesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this route get templates not found response has a 3xx status code
func (o *RouteGetTemplatesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get templates not found response has a 4xx status code
func (o *RouteGetTemplatesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this route get templates not found response has a 5xx status code
func (o *RouteGetTemplatesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this route get templates not found response a status code equal to that given
func (o *RouteGetTemplatesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the route get templates not found response
func (o *RouteGetTemplatesNotFound) Code() int {
	return 404
}

func (o *RouteGetTemplatesNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates][%d] routeGetTemplatesNotFound ", 404)
}

func (o *RouteGetTemplatesNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates][%d] routeGetTemplatesNotFound ", 404)
}

func (o *RouteGetTemplatesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
