// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RouteGetTemplateReader is a Reader for the RouteGetTemplate structure.
type RouteGetTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRouteGetTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/provisioning/templates/{name}] RouteGetTemplate", response, response.Code())
	}
}

// NewRouteGetTemplateOK creates a RouteGetTemplateOK with default headers values
func NewRouteGetTemplateOK() *RouteGetTemplateOK {
	return &RouteGetTemplateOK{}
}

/*
RouteGetTemplateOK describes a response with status code 200, with default header values.

NotificationTemplate
*/
type RouteGetTemplateOK struct {
	Payload *models.NotificationTemplate
}

// IsSuccess returns true when this route get template Ok response has a 2xx status code
func (o *RouteGetTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route get template Ok response has a 3xx status code
func (o *RouteGetTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get template Ok response has a 4xx status code
func (o *RouteGetTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route get template Ok response has a 5xx status code
func (o *RouteGetTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route get template Ok response a status code equal to that given
func (o *RouteGetTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the route get template Ok response
func (o *RouteGetTemplateOK) Code() int {
	return 200
}

func (o *RouteGetTemplateOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates/{name}][%d] routeGetTemplateOk  %+v", 200, o.Payload)
}

func (o *RouteGetTemplateOK) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates/{name}][%d] routeGetTemplateOk  %+v", 200, o.Payload)
}

func (o *RouteGetTemplateOK) GetPayload() *models.NotificationTemplate {
	return o.Payload
}

func (o *RouteGetTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NotificationTemplate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteGetTemplateNotFound creates a RouteGetTemplateNotFound with default headers values
func NewRouteGetTemplateNotFound() *RouteGetTemplateNotFound {
	return &RouteGetTemplateNotFound{}
}

/*
RouteGetTemplateNotFound describes a response with status code 404, with default header values.

	Not found.
*/
type RouteGetTemplateNotFound struct {
}

// IsSuccess returns true when this route get template not found response has a 2xx status code
func (o *RouteGetTemplateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this route get template not found response has a 3xx status code
func (o *RouteGetTemplateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get template not found response has a 4xx status code
func (o *RouteGetTemplateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this route get template not found response has a 5xx status code
func (o *RouteGetTemplateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this route get template not found response a status code equal to that given
func (o *RouteGetTemplateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the route get template not found response
func (o *RouteGetTemplateNotFound) Code() int {
	return 404
}

func (o *RouteGetTemplateNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates/{name}][%d] routeGetTemplateNotFound ", 404)
}

func (o *RouteGetTemplateNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/templates/{name}][%d] routeGetTemplateNotFound ", 404)
}

func (o *RouteGetTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
