// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RouteDeleteContactpointsReader is a Reader for the RouteDeleteContactpoints structure.
type RouteDeleteContactpointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteDeleteContactpointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRouteDeleteContactpointsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/provisioning/contact-points/{UID}] RouteDeleteContactpoints", response, response.Code())
	}
}

// NewRouteDeleteContactpointsNoContent creates a RouteDeleteContactpointsNoContent with default headers values
func NewRouteDeleteContactpointsNoContent() *RouteDeleteContactpointsNoContent {
	return &RouteDeleteContactpointsNoContent{}
}

/*
RouteDeleteContactpointsNoContent describes a response with status code 204, with default header values.

	The contact point was deleted successfully.
*/
type RouteDeleteContactpointsNoContent struct {
}

// IsSuccess returns true when this route delete contactpoints no content response has a 2xx status code
func (o *RouteDeleteContactpointsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route delete contactpoints no content response has a 3xx status code
func (o *RouteDeleteContactpointsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route delete contactpoints no content response has a 4xx status code
func (o *RouteDeleteContactpointsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this route delete contactpoints no content response has a 5xx status code
func (o *RouteDeleteContactpointsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this route delete contactpoints no content response a status code equal to that given
func (o *RouteDeleteContactpointsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the route delete contactpoints no content response
func (o *RouteDeleteContactpointsNoContent) Code() int {
	return 204
}

func (o *RouteDeleteContactpointsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/provisioning/contact-points/{UID}][%d] routeDeleteContactpointsNoContent ", 204)
}

func (o *RouteDeleteContactpointsNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v1/provisioning/contact-points/{UID}][%d] routeDeleteContactpointsNoContent ", 204)
}

func (o *RouteDeleteContactpointsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
