// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RouteGetAlertRuleExportReader is a Reader for the RouteGetAlertRuleExport structure.
type RouteGetAlertRuleExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetAlertRuleExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetAlertRuleExportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRouteGetAlertRuleExportNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/provisioning/alert-rules/{UID}/export] RouteGetAlertRuleExport", response, response.Code())
	}
}

// NewRouteGetAlertRuleExportOK creates a RouteGetAlertRuleExportOK with default headers values
func NewRouteGetAlertRuleExportOK() *RouteGetAlertRuleExportOK {
	return &RouteGetAlertRuleExportOK{}
}

/*
RouteGetAlertRuleExportOK describes a response with status code 200, with default header values.

AlertingFileExport
*/
type RouteGetAlertRuleExportOK struct {
	Payload *models.AlertingFileExport
}

// IsSuccess returns true when this route get alert rule export Ok response has a 2xx status code
func (o *RouteGetAlertRuleExportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route get alert rule export Ok response has a 3xx status code
func (o *RouteGetAlertRuleExportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get alert rule export Ok response has a 4xx status code
func (o *RouteGetAlertRuleExportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route get alert rule export Ok response has a 5xx status code
func (o *RouteGetAlertRuleExportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route get alert rule export Ok response a status code equal to that given
func (o *RouteGetAlertRuleExportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the route get alert rule export Ok response
func (o *RouteGetAlertRuleExportOK) Code() int {
	return 200
}

func (o *RouteGetAlertRuleExportOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/{UID}/export][%d] routeGetAlertRuleExportOk  %+v", 200, o.Payload)
}

func (o *RouteGetAlertRuleExportOK) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/{UID}/export][%d] routeGetAlertRuleExportOk  %+v", 200, o.Payload)
}

func (o *RouteGetAlertRuleExportOK) GetPayload() *models.AlertingFileExport {
	return o.Payload
}

func (o *RouteGetAlertRuleExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertingFileExport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteGetAlertRuleExportNotFound creates a RouteGetAlertRuleExportNotFound with default headers values
func NewRouteGetAlertRuleExportNotFound() *RouteGetAlertRuleExportNotFound {
	return &RouteGetAlertRuleExportNotFound{}
}

/*
RouteGetAlertRuleExportNotFound describes a response with status code 404, with default header values.

	Not found.
*/
type RouteGetAlertRuleExportNotFound struct {
}

// IsSuccess returns true when this route get alert rule export not found response has a 2xx status code
func (o *RouteGetAlertRuleExportNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this route get alert rule export not found response has a 3xx status code
func (o *RouteGetAlertRuleExportNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get alert rule export not found response has a 4xx status code
func (o *RouteGetAlertRuleExportNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this route get alert rule export not found response has a 5xx status code
func (o *RouteGetAlertRuleExportNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this route get alert rule export not found response a status code equal to that given
func (o *RouteGetAlertRuleExportNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the route get alert rule export not found response
func (o *RouteGetAlertRuleExportNotFound) Code() int {
	return 404
}

func (o *RouteGetAlertRuleExportNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/{UID}/export][%d] routeGetAlertRuleExportNotFound ", 404)
}

func (o *RouteGetAlertRuleExportNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/alert-rules/{UID}/export][%d] routeGetAlertRuleExportNotFound ", 404)
}

func (o *RouteGetAlertRuleExportNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
