// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RouteDeleteTemplateReader is a Reader for the RouteDeleteTemplate structure.
type RouteDeleteTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteDeleteTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRouteDeleteTemplateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/provisioning/templates/{name}] RouteDeleteTemplate", response, response.Code())
	}
}

// NewRouteDeleteTemplateNoContent creates a RouteDeleteTemplateNoContent with default headers values
func NewRouteDeleteTemplateNoContent() *RouteDeleteTemplateNoContent {
	return &RouteDeleteTemplateNoContent{}
}

/*
RouteDeleteTemplateNoContent describes a response with status code 204, with default header values.

	The template was deleted successfully.
*/
type RouteDeleteTemplateNoContent struct {
}

// IsSuccess returns true when this route delete template no content response has a 2xx status code
func (o *RouteDeleteTemplateNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route delete template no content response has a 3xx status code
func (o *RouteDeleteTemplateNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route delete template no content response has a 4xx status code
func (o *RouteDeleteTemplateNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this route delete template no content response has a 5xx status code
func (o *RouteDeleteTemplateNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this route delete template no content response a status code equal to that given
func (o *RouteDeleteTemplateNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the route delete template no content response
func (o *RouteDeleteTemplateNoContent) Code() int {
	return 204
}

func (o *RouteDeleteTemplateNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/provisioning/templates/{name}][%d] routeDeleteTemplateNoContent ", 204)
}

func (o *RouteDeleteTemplateNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v1/provisioning/templates/{name}][%d] routeDeleteTemplateNoContent ", 204)
}

func (o *RouteDeleteTemplateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
