// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// RouteGetAlertRuleGroupReader is a Reader for the RouteGetAlertRuleGroup structure.
type RouteGetAlertRuleGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RouteGetAlertRuleGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRouteGetAlertRuleGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRouteGetAlertRuleGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}] RouteGetAlertRuleGroup", response, response.Code())
	}
}

// NewRouteGetAlertRuleGroupOK creates a RouteGetAlertRuleGroupOK with default headers values
func NewRouteGetAlertRuleGroupOK() *RouteGetAlertRuleGroupOK {
	return &RouteGetAlertRuleGroupOK{}
}

/*
RouteGetAlertRuleGroupOK describes a response with status code 200, with default header values.

AlertRuleGroup
*/
type RouteGetAlertRuleGroupOK struct {
	Payload *models.AlertRuleGroup
}

// IsSuccess returns true when this route get alert rule group Ok response has a 2xx status code
func (o *RouteGetAlertRuleGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this route get alert rule group Ok response has a 3xx status code
func (o *RouteGetAlertRuleGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get alert rule group Ok response has a 4xx status code
func (o *RouteGetAlertRuleGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this route get alert rule group Ok response has a 5xx status code
func (o *RouteGetAlertRuleGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this route get alert rule group Ok response a status code equal to that given
func (o *RouteGetAlertRuleGroupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the route get alert rule group Ok response
func (o *RouteGetAlertRuleGroupOK) Code() int {
	return 200
}

func (o *RouteGetAlertRuleGroupOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}][%d] routeGetAlertRuleGroupOk  %+v", 200, o.Payload)
}

func (o *RouteGetAlertRuleGroupOK) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}][%d] routeGetAlertRuleGroupOk  %+v", 200, o.Payload)
}

func (o *RouteGetAlertRuleGroupOK) GetPayload() *models.AlertRuleGroup {
	return o.Payload
}

func (o *RouteGetAlertRuleGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AlertRuleGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRouteGetAlertRuleGroupNotFound creates a RouteGetAlertRuleGroupNotFound with default headers values
func NewRouteGetAlertRuleGroupNotFound() *RouteGetAlertRuleGroupNotFound {
	return &RouteGetAlertRuleGroupNotFound{}
}

/*
RouteGetAlertRuleGroupNotFound describes a response with status code 404, with default header values.

	Not found.
*/
type RouteGetAlertRuleGroupNotFound struct {
}

// IsSuccess returns true when this route get alert rule group not found response has a 2xx status code
func (o *RouteGetAlertRuleGroupNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this route get alert rule group not found response has a 3xx status code
func (o *RouteGetAlertRuleGroupNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this route get alert rule group not found response has a 4xx status code
func (o *RouteGetAlertRuleGroupNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this route get alert rule group not found response has a 5xx status code
func (o *RouteGetAlertRuleGroupNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this route get alert rule group not found response a status code equal to that given
func (o *RouteGetAlertRuleGroupNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the route get alert rule group not found response
func (o *RouteGetAlertRuleGroupNotFound) Code() int {
	return 404
}

func (o *RouteGetAlertRuleGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}][%d] routeGetAlertRuleGroupNotFound ", 404)
}

func (o *RouteGetAlertRuleGroupNotFound) String() string {
	return fmt.Sprintf("[GET /api/v1/provisioning/folder/{FolderUID}/rule-groups/{Group}][%d] routeGetAlertRuleGroupNotFound ", 404)
}

func (o *RouteGetAlertRuleGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
