// Code generated by go-swagger; DO NOT EDIT.

package provisioning

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRouteGetPolicyTreeExportParams creates a new RouteGetPolicyTreeExportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRouteGetPolicyTreeExportParams() *RouteGetPolicyTreeExportParams {
	return &RouteGetPolicyTreeExportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRouteGetPolicyTreeExportParamsWithTimeout creates a new RouteGetPolicyTreeExportParams object
// with the ability to set a timeout on a request.
func NewRouteGetPolicyTreeExportParamsWithTimeout(timeout time.Duration) *RouteGetPolicyTreeExportParams {
	return &RouteGetPolicyTreeExportParams{
		timeout: timeout,
	}
}

// NewRouteGetPolicyTreeExportParamsWithContext creates a new RouteGetPolicyTreeExportParams object
// with the ability to set a context for a request.
func NewRouteGetPolicyTreeExportParamsWithContext(ctx context.Context) *RouteGetPolicyTreeExportParams {
	return &RouteGetPolicyTreeExportParams{
		Context: ctx,
	}
}

// NewRouteGetPolicyTreeExportParamsWithHTTPClient creates a new RouteGetPolicyTreeExportParams object
// with the ability to set a custom HTTPClient for a request.
func NewRouteGetPolicyTreeExportParamsWithHTTPClient(client *http.Client) *RouteGetPolicyTreeExportParams {
	return &RouteGetPolicyTreeExportParams{
		HTTPClient: client,
	}
}

/*
RouteGetPolicyTreeExportParams contains all the parameters to send to the API endpoint

	for the route get policy tree export operation.

	Typically these are written to a http.Request.
*/
type RouteGetPolicyTreeExportParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the route get policy tree export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetPolicyTreeExportParams) WithDefaults() *RouteGetPolicyTreeExportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the route get policy tree export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RouteGetPolicyTreeExportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the route get policy tree export params
func (o *RouteGetPolicyTreeExportParams) WithTimeout(timeout time.Duration) *RouteGetPolicyTreeExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the route get policy tree export params
func (o *RouteGetPolicyTreeExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the route get policy tree export params
func (o *RouteGetPolicyTreeExportParams) WithContext(ctx context.Context) *RouteGetPolicyTreeExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the route get policy tree export params
func (o *RouteGetPolicyTreeExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the route get policy tree export params
func (o *RouteGetPolicyTreeExportParams) WithHTTPClient(client *http.Client) *RouteGetPolicyTreeExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the route get policy tree export params
func (o *RouteGetPolicyTreeExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RouteGetPolicyTreeExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
