// Code generated by go-swagger; DO NOT EDIT.

package group_attribute_sync

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupMappingParams creates a new GetGroupMappingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupMappingParams() *GetGroupMappingParams {
	return &GetGroupMappingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupMappingParamsWithTimeout creates a new GetGroupMappingParams object
// with the ability to set a timeout on a request.
func NewGetGroupMappingParamsWithTimeout(timeout time.Duration) *GetGroupMappingParams {
	return &GetGroupMappingParams{
		timeout: timeout,
	}
}

// NewGetGroupMappingParamsWithContext creates a new GetGroupMappingParams object
// with the ability to set a context for a request.
func NewGetGroupMappingParamsWithContext(ctx context.Context) *GetGroupMappingParams {
	return &GetGroupMappingParams{
		Context: ctx,
	}
}

// NewGetGroupMappingParamsWithHTTPClient creates a new GetGroupMappingParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupMappingParamsWithHTTPClient(client *http.Client) *GetGroupMappingParams {
	return &GetGroupMappingParams{
		HTTPClient: client,
	}
}

/*
GetGroupMappingParams contains all the parameters to send to the API endpoint

	for the get group mapping operation.

	Typically these are written to a http.Request.
*/
type GetGroupMappingParams struct {

	// MappingUID.
	MappingUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get group mapping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupMappingParams) WithDefaults() *GetGroupMappingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get group mapping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupMappingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get group mapping params
func (o *GetGroupMappingParams) WithTimeout(timeout time.Duration) *GetGroupMappingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group mapping params
func (o *GetGroupMappingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group mapping params
func (o *GetGroupMappingParams) WithContext(ctx context.Context) *GetGroupMappingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group mapping params
func (o *GetGroupMappingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group mapping params
func (o *GetGroupMappingParams) WithHTTPClient(client *http.Client) *GetGroupMappingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group mapping params
func (o *GetGroupMappingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMappingUID adds the mappingUID to the get group mapping params
func (o *GetGroupMappingParams) WithMappingUID(mappingUID string) *GetGroupMappingParams {
	o.SetMappingUID(mappingUID)
	return o
}

// SetMappingUID adds the mappingUid to the get group mapping params
func (o *GetGroupMappingParams) SetMappingUID(mappingUID string) {
	o.MappingUID = mappingUID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupMappingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param mapping_uid
	if err := r.SetPathParam("mapping_uid", o.MappingUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
