// Code generated by go-swagger; DO NOT EDIT.

package group_attribute_sync

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGroupMappingsParams creates a new GetGroupMappingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupMappingsParams() *GetGroupMappingsParams {
	return &GetGroupMappingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupMappingsParamsWithTimeout creates a new GetGroupMappingsParams object
// with the ability to set a timeout on a request.
func NewGetGroupMappingsParamsWithTimeout(timeout time.Duration) *GetGroupMappingsParams {
	return &GetGroupMappingsParams{
		timeout: timeout,
	}
}

// NewGetGroupMappingsParamsWithContext creates a new GetGroupMappingsParams object
// with the ability to set a context for a request.
func NewGetGroupMappingsParamsWithContext(ctx context.Context) *GetGroupMappingsParams {
	return &GetGroupMappingsParams{
		Context: ctx,
	}
}

// NewGetGroupMappingsParamsWithHTTPClient creates a new GetGroupMappingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupMappingsParamsWithHTTPClient(client *http.Client) *GetGroupMappingsParams {
	return &GetGroupMappingsParams{
		HTTPClient: client,
	}
}

/*
GetGroupMappingsParams contains all the parameters to send to the API endpoint

	for the get group mappings operation.

	Typically these are written to a http.Request.
*/
type GetGroupMappingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get group mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupMappingsParams) WithDefaults() *GetGroupMappingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get group mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupMappingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get group mappings params
func (o *GetGroupMappingsParams) WithTimeout(timeout time.Duration) *GetGroupMappingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group mappings params
func (o *GetGroupMappingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group mappings params
func (o *GetGroupMappingsParams) WithContext(ctx context.Context) *GetGroupMappingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group mappings params
func (o *GetGroupMappingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group mappings params
func (o *GetGroupMappingsParams) WithHTTPClient(client *http.Client) *GetGroupMappingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group mappings params
func (o *GetGroupMappingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupMappingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
