// Code generated by go-swagger; DO NOT EDIT.

package migrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// CreateMigrationReader is a Reader for the CreateMigration structure.
type CreateMigrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMigrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateMigrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateMigrationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateMigrationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateMigrationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /cloudmigration/migration] createMigration", response, response.Code())
	}
}

// NewCreateMigrationOK creates a CreateMigrationOK with default headers values
func NewCreateMigrationOK() *CreateMigrationOK {
	return &CreateMigrationOK{}
}

/*
CreateMigrationOK describes a response with status code 200, with default header values.

(empty)
*/
type CreateMigrationOK struct {
	Payload *models.CloudMigrationResponse
}

// IsSuccess returns true when this create migration Ok response has a 2xx status code
func (o *CreateMigrationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create migration Ok response has a 3xx status code
func (o *CreateMigrationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create migration Ok response has a 4xx status code
func (o *CreateMigrationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create migration Ok response has a 5xx status code
func (o *CreateMigrationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create migration Ok response a status code equal to that given
func (o *CreateMigrationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create migration Ok response
func (o *CreateMigrationOK) Code() int {
	return 200
}

func (o *CreateMigrationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationOk %s", 200, payload)
}

func (o *CreateMigrationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationOk %s", 200, payload)
}

func (o *CreateMigrationOK) GetPayload() *models.CloudMigrationResponse {
	return o.Payload
}

func (o *CreateMigrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudMigrationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMigrationUnauthorized creates a CreateMigrationUnauthorized with default headers values
func NewCreateMigrationUnauthorized() *CreateMigrationUnauthorized {
	return &CreateMigrationUnauthorized{}
}

/*
CreateMigrationUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type CreateMigrationUnauthorized struct {
	Payload *models.ErrorResponseBody
}

// IsSuccess returns true when this create migration unauthorized response has a 2xx status code
func (o *CreateMigrationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create migration unauthorized response has a 3xx status code
func (o *CreateMigrationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create migration unauthorized response has a 4xx status code
func (o *CreateMigrationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create migration unauthorized response has a 5xx status code
func (o *CreateMigrationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create migration unauthorized response a status code equal to that given
func (o *CreateMigrationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create migration unauthorized response
func (o *CreateMigrationUnauthorized) Code() int {
	return 401
}

func (o *CreateMigrationUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationUnauthorized %s", 401, payload)
}

func (o *CreateMigrationUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationUnauthorized %s", 401, payload)
}

func (o *CreateMigrationUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *CreateMigrationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMigrationForbidden creates a CreateMigrationForbidden with default headers values
func NewCreateMigrationForbidden() *CreateMigrationForbidden {
	return &CreateMigrationForbidden{}
}

/*
CreateMigrationForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type CreateMigrationForbidden struct {
	Payload *models.ErrorResponseBody
}

// IsSuccess returns true when this create migration forbidden response has a 2xx status code
func (o *CreateMigrationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create migration forbidden response has a 3xx status code
func (o *CreateMigrationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create migration forbidden response has a 4xx status code
func (o *CreateMigrationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create migration forbidden response has a 5xx status code
func (o *CreateMigrationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create migration forbidden response a status code equal to that given
func (o *CreateMigrationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create migration forbidden response
func (o *CreateMigrationForbidden) Code() int {
	return 403
}

func (o *CreateMigrationForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationForbidden %s", 403, payload)
}

func (o *CreateMigrationForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationForbidden %s", 403, payload)
}

func (o *CreateMigrationForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *CreateMigrationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateMigrationInternalServerError creates a CreateMigrationInternalServerError with default headers values
func NewCreateMigrationInternalServerError() *CreateMigrationInternalServerError {
	return &CreateMigrationInternalServerError{}
}

/*
CreateMigrationInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type CreateMigrationInternalServerError struct {
	Payload *models.ErrorResponseBody
}

// IsSuccess returns true when this create migration internal server error response has a 2xx status code
func (o *CreateMigrationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create migration internal server error response has a 3xx status code
func (o *CreateMigrationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create migration internal server error response has a 4xx status code
func (o *CreateMigrationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create migration internal server error response has a 5xx status code
func (o *CreateMigrationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create migration internal server error response a status code equal to that given
func (o *CreateMigrationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create migration internal server error response
func (o *CreateMigrationInternalServerError) Code() int {
	return 500
}

func (o *CreateMigrationInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationInternalServerError %s", 500, payload)
}

func (o *CreateMigrationInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cloudmigration/migration][%d] createMigrationInternalServerError %s", 500, payload)
}

func (o *CreateMigrationInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *CreateMigrationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
