// Code generated by go-swagger; DO NOT EDIT.

package migrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCloudMigrationParams creates a new DeleteCloudMigrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCloudMigrationParams() *DeleteCloudMigrationParams {
	return &DeleteCloudMigrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCloudMigrationParamsWithTimeout creates a new DeleteCloudMigrationParams object
// with the ability to set a timeout on a request.
func NewDeleteCloudMigrationParamsWithTimeout(timeout time.Duration) *DeleteCloudMigrationParams {
	return &DeleteCloudMigrationParams{
		timeout: timeout,
	}
}

// NewDeleteCloudMigrationParamsWithContext creates a new DeleteCloudMigrationParams object
// with the ability to set a context for a request.
func NewDeleteCloudMigrationParamsWithContext(ctx context.Context) *DeleteCloudMigrationParams {
	return &DeleteCloudMigrationParams{
		Context: ctx,
	}
}

// NewDeleteCloudMigrationParamsWithHTTPClient creates a new DeleteCloudMigrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCloudMigrationParamsWithHTTPClient(client *http.Client) *DeleteCloudMigrationParams {
	return &DeleteCloudMigrationParams{
		HTTPClient: client,
	}
}

/*
DeleteCloudMigrationParams contains all the parameters to send to the API endpoint

	for the delete cloud migration operation.

	Typically these are written to a http.Request.
*/
type DeleteCloudMigrationParams struct {

	/* UID.

	   UID of a migration
	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete cloud migration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCloudMigrationParams) WithDefaults() *DeleteCloudMigrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete cloud migration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCloudMigrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete cloud migration params
func (o *DeleteCloudMigrationParams) WithTimeout(timeout time.Duration) *DeleteCloudMigrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cloud migration params
func (o *DeleteCloudMigrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cloud migration params
func (o *DeleteCloudMigrationParams) WithContext(ctx context.Context) *DeleteCloudMigrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cloud migration params
func (o *DeleteCloudMigrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cloud migration params
func (o *DeleteCloudMigrationParams) WithHTTPClient(client *http.Client) *DeleteCloudMigrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cloud migration params
func (o *DeleteCloudMigrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the delete cloud migration params
func (o *DeleteCloudMigrationParams) WithUID(uid string) *DeleteCloudMigrationParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the delete cloud migration params
func (o *DeleteCloudMigrationParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCloudMigrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
