// Code generated by go-swagger; DO NOT EDIT.

package migrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/grafana/grafana-openapi-client-go/models"
)

// GetCloudMigrationRunListReader is a Reader for the GetCloudMigrationRunList structure.
type GetCloudMigrationRunListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCloudMigrationRunListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCloudMigrationRunListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCloudMigrationRunListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetCloudMigrationRunListForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCloudMigrationRunListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /cloudmigration/migration/{uid}/run] getCloudMigrationRunList", response, response.Code())
	}
}

// NewGetCloudMigrationRunListOK creates a GetCloudMigrationRunListOK with default headers values
func NewGetCloudMigrationRunListOK() *GetCloudMigrationRunListOK {
	return &GetCloudMigrationRunListOK{}
}

/*
GetCloudMigrationRunListOK describes a response with status code 200, with default header values.

(empty)
*/
type GetCloudMigrationRunListOK struct {
	Payload *models.CloudMigrationRunList
}

// IsSuccess returns true when this get cloud migration run list Ok response has a 2xx status code
func (o *GetCloudMigrationRunListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cloud migration run list Ok response has a 3xx status code
func (o *GetCloudMigrationRunListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud migration run list Ok response has a 4xx status code
func (o *GetCloudMigrationRunListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cloud migration run list Ok response has a 5xx status code
func (o *GetCloudMigrationRunListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud migration run list Ok response a status code equal to that given
func (o *GetCloudMigrationRunListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get cloud migration run list Ok response
func (o *GetCloudMigrationRunListOK) Code() int {
	return 200
}

func (o *GetCloudMigrationRunListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListOk %s", 200, payload)
}

func (o *GetCloudMigrationRunListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListOk %s", 200, payload)
}

func (o *GetCloudMigrationRunListOK) GetPayload() *models.CloudMigrationRunList {
	return o.Payload
}

func (o *GetCloudMigrationRunListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudMigrationRunList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudMigrationRunListUnauthorized creates a GetCloudMigrationRunListUnauthorized with default headers values
func NewGetCloudMigrationRunListUnauthorized() *GetCloudMigrationRunListUnauthorized {
	return &GetCloudMigrationRunListUnauthorized{}
}

/*
GetCloudMigrationRunListUnauthorized describes a response with status code 401, with default header values.

UnauthorizedError is returned when the request is not authenticated.
*/
type GetCloudMigrationRunListUnauthorized struct {
	Payload *models.ErrorResponseBody
}

// IsSuccess returns true when this get cloud migration run list unauthorized response has a 2xx status code
func (o *GetCloudMigrationRunListUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud migration run list unauthorized response has a 3xx status code
func (o *GetCloudMigrationRunListUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud migration run list unauthorized response has a 4xx status code
func (o *GetCloudMigrationRunListUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cloud migration run list unauthorized response has a 5xx status code
func (o *GetCloudMigrationRunListUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud migration run list unauthorized response a status code equal to that given
func (o *GetCloudMigrationRunListUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get cloud migration run list unauthorized response
func (o *GetCloudMigrationRunListUnauthorized) Code() int {
	return 401
}

func (o *GetCloudMigrationRunListUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListUnauthorized %s", 401, payload)
}

func (o *GetCloudMigrationRunListUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListUnauthorized %s", 401, payload)
}

func (o *GetCloudMigrationRunListUnauthorized) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCloudMigrationRunListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudMigrationRunListForbidden creates a GetCloudMigrationRunListForbidden with default headers values
func NewGetCloudMigrationRunListForbidden() *GetCloudMigrationRunListForbidden {
	return &GetCloudMigrationRunListForbidden{}
}

/*
GetCloudMigrationRunListForbidden describes a response with status code 403, with default header values.

ForbiddenError is returned if the user/token has insufficient permissions to access the requested resource.
*/
type GetCloudMigrationRunListForbidden struct {
	Payload *models.ErrorResponseBody
}

// IsSuccess returns true when this get cloud migration run list forbidden response has a 2xx status code
func (o *GetCloudMigrationRunListForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud migration run list forbidden response has a 3xx status code
func (o *GetCloudMigrationRunListForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud migration run list forbidden response has a 4xx status code
func (o *GetCloudMigrationRunListForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cloud migration run list forbidden response has a 5xx status code
func (o *GetCloudMigrationRunListForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud migration run list forbidden response a status code equal to that given
func (o *GetCloudMigrationRunListForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get cloud migration run list forbidden response
func (o *GetCloudMigrationRunListForbidden) Code() int {
	return 403
}

func (o *GetCloudMigrationRunListForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListForbidden %s", 403, payload)
}

func (o *GetCloudMigrationRunListForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListForbidden %s", 403, payload)
}

func (o *GetCloudMigrationRunListForbidden) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCloudMigrationRunListForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudMigrationRunListInternalServerError creates a GetCloudMigrationRunListInternalServerError with default headers values
func NewGetCloudMigrationRunListInternalServerError() *GetCloudMigrationRunListInternalServerError {
	return &GetCloudMigrationRunListInternalServerError{}
}

/*
GetCloudMigrationRunListInternalServerError describes a response with status code 500, with default header values.

InternalServerError is a general error indicating something went wrong internally.
*/
type GetCloudMigrationRunListInternalServerError struct {
	Payload *models.ErrorResponseBody
}

// IsSuccess returns true when this get cloud migration run list internal server error response has a 2xx status code
func (o *GetCloudMigrationRunListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud migration run list internal server error response has a 3xx status code
func (o *GetCloudMigrationRunListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud migration run list internal server error response has a 4xx status code
func (o *GetCloudMigrationRunListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cloud migration run list internal server error response has a 5xx status code
func (o *GetCloudMigrationRunListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get cloud migration run list internal server error response a status code equal to that given
func (o *GetCloudMigrationRunListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get cloud migration run list internal server error response
func (o *GetCloudMigrationRunListInternalServerError) Code() int {
	return 500
}

func (o *GetCloudMigrationRunListInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListInternalServerError %s", 500, payload)
}

func (o *GetCloudMigrationRunListInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloudmigration/migration/{uid}/run][%d] getCloudMigrationRunListInternalServerError %s", 500, payload)
}

func (o *GetCloudMigrationRunListInternalServerError) GetPayload() *models.ErrorResponseBody {
	return o.Payload
}

func (o *GetCloudMigrationRunListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponseBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
