// Code generated by go-swagger; DO NOT EDIT.

package migrations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRunCloudMigrationParams creates a new RunCloudMigrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRunCloudMigrationParams() *RunCloudMigrationParams {
	return &RunCloudMigrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRunCloudMigrationParamsWithTimeout creates a new RunCloudMigrationParams object
// with the ability to set a timeout on a request.
func NewRunCloudMigrationParamsWithTimeout(timeout time.Duration) *RunCloudMigrationParams {
	return &RunCloudMigrationParams{
		timeout: timeout,
	}
}

// NewRunCloudMigrationParamsWithContext creates a new RunCloudMigrationParams object
// with the ability to set a context for a request.
func NewRunCloudMigrationParamsWithContext(ctx context.Context) *RunCloudMigrationParams {
	return &RunCloudMigrationParams{
		Context: ctx,
	}
}

// NewRunCloudMigrationParamsWithHTTPClient creates a new RunCloudMigrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewRunCloudMigrationParamsWithHTTPClient(client *http.Client) *RunCloudMigrationParams {
	return &RunCloudMigrationParams{
		HTTPClient: client,
	}
}

/*
RunCloudMigrationParams contains all the parameters to send to the API endpoint

	for the run cloud migration operation.

	Typically these are written to a http.Request.
*/
type RunCloudMigrationParams struct {

	/* UID.

	   UID of a migration
	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the run cloud migration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunCloudMigrationParams) WithDefaults() *RunCloudMigrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the run cloud migration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunCloudMigrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the run cloud migration params
func (o *RunCloudMigrationParams) WithTimeout(timeout time.Duration) *RunCloudMigrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the run cloud migration params
func (o *RunCloudMigrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the run cloud migration params
func (o *RunCloudMigrationParams) WithContext(ctx context.Context) *RunCloudMigrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the run cloud migration params
func (o *RunCloudMigrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the run cloud migration params
func (o *RunCloudMigrationParams) WithHTTPClient(client *http.Client) *RunCloudMigrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the run cloud migration params
func (o *RunCloudMigrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the run cloud migration params
func (o *RunCloudMigrationParams) WithUID(uid string) *RunCloudMigrationParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the run cloud migration params
func (o *RunCloudMigrationParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *RunCloudMigrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
