// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHardDeleteDashboardByUIDParams creates a new HardDeleteDashboardByUIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHardDeleteDashboardByUIDParams() *HardDeleteDashboardByUIDParams {
	return &HardDeleteDashboardByUIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHardDeleteDashboardByUIDParamsWithTimeout creates a new HardDeleteDashboardByUIDParams object
// with the ability to set a timeout on a request.
func NewHardDeleteDashboardByUIDParamsWithTimeout(timeout time.Duration) *HardDeleteDashboardByUIDParams {
	return &HardDeleteDashboardByUIDParams{
		timeout: timeout,
	}
}

// NewHardDeleteDashboardByUIDParamsWithContext creates a new HardDeleteDashboardByUIDParams object
// with the ability to set a context for a request.
func NewHardDeleteDashboardByUIDParamsWithContext(ctx context.Context) *HardDeleteDashboardByUIDParams {
	return &HardDeleteDashboardByUIDParams{
		Context: ctx,
	}
}

// NewHardDeleteDashboardByUIDParamsWithHTTPClient creates a new HardDeleteDashboardByUIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewHardDeleteDashboardByUIDParamsWithHTTPClient(client *http.Client) *HardDeleteDashboardByUIDParams {
	return &HardDeleteDashboardByUIDParams{
		HTTPClient: client,
	}
}

/*
HardDeleteDashboardByUIDParams contains all the parameters to send to the API endpoint

	for the hard delete dashboard by UID operation.

	Typically these are written to a http.Request.
*/
type HardDeleteDashboardByUIDParams struct {

	// UID.
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the hard delete dashboard by UID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HardDeleteDashboardByUIDParams) WithDefaults() *HardDeleteDashboardByUIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the hard delete dashboard by UID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HardDeleteDashboardByUIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) WithTimeout(timeout time.Duration) *HardDeleteDashboardByUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) WithContext(ctx context.Context) *HardDeleteDashboardByUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) WithHTTPClient(client *http.Client) *HardDeleteDashboardByUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUID adds the uid to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) WithUID(uid string) *HardDeleteDashboardByUIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the hard delete dashboard by UID params
func (o *HardDeleteDashboardByUIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *HardDeleteDashboardByUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
