// Code generated by go-swagger; DO NOT EDIT.

package correlations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCorrelationsParams creates a new GetCorrelationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCorrelationsParams() *GetCorrelationsParams {
	return &GetCorrelationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCorrelationsParamsWithTimeout creates a new GetCorrelationsParams object
// with the ability to set a timeout on a request.
func NewGetCorrelationsParamsWithTimeout(timeout time.Duration) *GetCorrelationsParams {
	return &GetCorrelationsParams{
		timeout: timeout,
	}
}

// NewGetCorrelationsParamsWithContext creates a new GetCorrelationsParams object
// with the ability to set a context for a request.
func NewGetCorrelationsParamsWithContext(ctx context.Context) *GetCorrelationsParams {
	return &GetCorrelationsParams{
		Context: ctx,
	}
}

// NewGetCorrelationsParamsWithHTTPClient creates a new GetCorrelationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCorrelationsParamsWithHTTPClient(client *http.Client) *GetCorrelationsParams {
	return &GetCorrelationsParams{
		HTTPClient: client,
	}
}

/*
GetCorrelationsParams contains all the parameters to send to the API endpoint

	for the get correlations operation.

	Typically these are written to a http.Request.
*/
type GetCorrelationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get correlations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCorrelationsParams) WithDefaults() *GetCorrelationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get correlations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCorrelationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get correlations params
func (o *GetCorrelationsParams) WithTimeout(timeout time.Duration) *GetCorrelationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get correlations params
func (o *GetCorrelationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get correlations params
func (o *GetCorrelationsParams) WithContext(ctx context.Context) *GetCorrelationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get correlations params
func (o *GetCorrelationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get correlations params
func (o *GetCorrelationsParams) WithHTTPClient(client *http.Client) *GetCorrelationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get correlations params
func (o *GetCorrelationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCorrelationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
