name: Check diff

# Generate the client and check that there's no diff

on:
    pull_request: {}

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.21
            - run: make generate-client
            - name: Check diff
              run: |
                  git diff --exit-code
