// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AlertRuleUpgrade alert rule upgrade
//
// swagger:model AlertRuleUpgrade
type AlertRuleUpgrade struct {

	// sends to
	SendsTo []string `json:"sendsTo"`

	// title
	Title string `json:"title,omitempty"`

	// uid
	UID string `json:"uid,omitempty"`
}

// Validate validates this alert rule upgrade
func (m *AlertRuleUpgrade) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this alert rule upgrade based on context it is used
func (m *AlertRuleUpgrade) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AlertRuleUpgrade) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AlertRuleUpgrade) UnmarshalBinary(b []byte) error {
	var res AlertRuleUpgrade
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
