// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContactPointUpgrade contact point upgrade
//
// swagger:model ContactPointUpgrade
type ContactPointUpgrade struct {

	// name
	Name string `json:"name,omitempty"`

	// route matchers
	RouteMatchers ObjectMatchers `json:"routeMatchers,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this contact point upgrade
func (m *ContactPointUpgrade) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRouteMatchers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContactPointUpgrade) validateRouteMatchers(formats strfmt.Registry) error {
	if swag.IsZero(m.RouteMatchers) { // not required
		return nil
	}

	if err := m.RouteMatchers.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("routeMatchers")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("routeMatchers")
		}
		return err
	}

	return nil
}

// ContextValidate validate this contact point upgrade based on the context it is used
func (m *ContactPointUpgrade) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRouteMatchers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContactPointUpgrade) contextValidateRouteMatchers(ctx context.Context, formats strfmt.Registry) error {

	if err := m.RouteMatchers.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("routeMatchers")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("routeMatchers")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContactPointUpgrade) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContactPointUpgrade) UnmarshalBinary(b []byte) error {
	var res ContactPointUpgrade
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
