// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CookieType cookie type
//
// swagger:model CookieType
type CookieType string

// Validate validates this cookie type
func (m CookieType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cookie type based on context it is used
func (m CookieType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
