// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GettableTimeIntervals gettable time intervals
//
// swagger:model GettableTimeIntervals
type GettableTimeIntervals struct {

	// name
	Name string `json:"name,omitempty"`

	// provenance
	Provenance Provenance `json:"provenance,omitempty"`

	// time intervals
	TimeIntervals []*TimeIntervalItem `json:"time_intervals"`
}

// Validate validates this gettable time intervals
func (m *GettableTimeIntervals) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProvenance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeIntervals(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GettableTimeIntervals) validateProvenance(formats strfmt.Registry) error {
	if swag.IsZero(m.Provenance) { // not required
		return nil
	}

	if err := m.Provenance.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("provenance")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("provenance")
		}
		return err
	}

	return nil
}

func (m *GettableTimeIntervals) validateTimeIntervals(formats strfmt.Registry) error {
	if swag.IsZero(m.TimeIntervals) { // not required
		return nil
	}

	for i := 0; i < len(m.TimeIntervals); i++ {
		if swag.IsZero(m.TimeIntervals[i]) { // not required
			continue
		}

		if m.TimeIntervals[i] != nil {
			if err := m.TimeIntervals[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("time_intervals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("time_intervals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this gettable time intervals based on the context it is used
func (m *GettableTimeIntervals) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProvenance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTimeIntervals(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GettableTimeIntervals) contextValidateProvenance(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Provenance) { // not required
		return nil
	}

	if err := m.Provenance.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("provenance")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("provenance")
		}
		return err
	}

	return nil
}

func (m *GettableTimeIntervals) contextValidateTimeIntervals(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TimeIntervals); i++ {

		if m.TimeIntervals[i] != nil {

			if swag.IsZero(m.TimeIntervals[i]) { // not required
				return nil
			}

			if err := m.TimeIntervals[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("time_intervals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("time_intervals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GettableTimeIntervals) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GettableTimeIntervals) UnmarshalBinary(b []byte) error {
	var res GettableTimeIntervals
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
