// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchProviderSettingsParamsBody patch provider settings params body
//
// swagger:model patchProviderSettingsParamsBody
type PatchProviderSettingsParamsBody struct {

	// settings
	Settings interface{} `json:"settings,omitempty"`
}

// Validate validates this patch provider settings params body
func (m *PatchProviderSettingsParamsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this patch provider settings params body based on context it is used
func (m *PatchProviderSettingsParamsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchProviderSettingsParamsBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchProviderSettingsParamsBody) UnmarshalBinary(b []byte) error {
	var res PatchProviderSettingsParamsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
