// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoteWriteConfig remote write config
//
// swagger:model RemoteWriteConfig
type RemoteWriteConfig struct {

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this remote write config
func (m *RemoteWriteConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this remote write config based on context it is used
func (m *RemoteWriteConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RemoteWriteConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoteWriteConfig) UnmarshalBinary(b []byte) error {
	var res RemoteWriteConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
