// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestoreDeletedDashboardCommand restore deleted dashboard command
//
// swagger:model RestoreDeletedDashboardCommand
type RestoreDeletedDashboardCommand struct {

	// folder Uid
	FolderUID string `json:"folderUid,omitempty"`
}

// Validate validates this restore deleted dashboard command
func (m *RestoreDeletedDashboardCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this restore deleted dashboard command based on context it is used
func (m *RestoreDeletedDashboardCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestoreDeletedDashboardCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestoreDeletedDashboardCommand) UnmarshalBinary(b []byte) error {
	var res RestoreDeletedDashboardCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
