// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SecretURL secret URL
//
// swagger:model SecretURL
type SecretURL string

// Validate validates this secret URL
func (m SecretURL) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret URL based on context it is used
func (m SecretURL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
