// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/grafana/grafana-openapi-client-go/pkg/custom_models"
)

// UpdateAnnotationsCmd update annotations cmd
//
// swagger:model UpdateAnnotationsCmd
type UpdateAnnotationsCmd struct {

	// data
	Data custom_models.JSON `json:"data,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// tags
	Tags []string `json:"tags"`

	// text
	Text string `json:"text,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`

	// time end
	TimeEnd int64 `json:"timeEnd,omitempty"`
}

// Validate validates this update annotations cmd
func (m *UpdateAnnotationsCmd) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateAnnotationsCmd) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	return nil
}

// ContextValidate validates this update annotations cmd based on context it is used
func (m *UpdateAnnotationsCmd) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateAnnotationsCmd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateAnnotationsCmd) UnmarshalBinary(b []byte) error {
	var res UpdateAnnotationsCmd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
