// Code generated by go-swagger; DO NOT EDIT.

package models

// Userinfo The Userinfo type is an immutable encapsulation of username and
// password details for a [URL]. An existing Userinfo value is guaranteed
// to have a username set (potentially empty, as allowed by RFC 2396),
// and optionally a password.
//
// swagger:model Userinfo
type Userinfo any
